baseURL = "https://house-intellect.github.io/automated-load-management-system/"

# The "title" of your website
title = "Автоматизированная Система Управления Нагрузкой - АСУН"
author = "house-intellect"
languageCode = "ru"
DefaultContentLanguage = "ru"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = false  # Disable relative URLs

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']
  copyright = "house-intellect"
  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "Автоматизированная Система Управления Нагрузкой - АСУН"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Автоматизированная Система Управления Нагрузкой"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Мы помогаем предприятиям и организациям активно управлять своим энергопотреблением, снижая затраты, повышая устойчивость энергосистемы и способствуя сохранению окружающей среды"
    meta_og_description = "Инновационное приложение для управления энергопотреблением, которое обеспечивает автономный контроль и оптимизацию работы вашей электрической сети"
    meta_og_type = "website"
    meta_og_url = "https://house-intellect.github.io/automated-load-management-system/"
    meta_og_image = "https://house-intellect.github.io/automated-load-management-system/images/tease.jpg"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"
    meta_og_title = "Автоматизированная Система Управления Нагрузкой"
    keywords = "АСУН, Автоматизированная Система Управления Нагрузкой, Demand-Side Management (DSM), Управление энергопотреблением, Оптимизация энергопотребления, Снижение затрат на электроэнергию, Энергоэффективность, Энергосбережение, Мониторинг энергопотребления, Контроль энергопотребления, Автоматизация управления нагрузкой, Управление пиковой нагрузкой, Снижение пиковой мощности, Demand Response (Управление спросом), Интеграция с программами управления спросом, Решения для энергоэффективности, Энергетический менеджмент, Системы управления энергопотреблением, Программное обеспечение для управления энергопотреблением"

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Проекты"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Новости"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "О нас"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Контакты"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Главная"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/house-intellect"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
