baseURL = "https://house-intellect.github.io/automated-load-management-system"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]

defaultContentLanguage = "ru"

# The name of this wonderful theme ;-).
theme = "hugo-product-launch"

# The "title" of your website
title = "Автоматизированная Система Управления Нагрузкой - АСУН"

# Render line-breaks in .md-files as line-breaks in HTML.
# This is e.g. useful for rendering a multi-line address.
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© house-intellect"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Мы помогаем предприятиям и организациям активно управлять своим энергопотреблением, снижая затраты, повышая устойчивость энергосистемы и способствуя сохранению окружающей среды"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/share-image.png"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Автоматизированная Система Управления Нагрузкой"



    [params.meta]
        keywords = "АСУН, Автоматизированная Система Управления Нагрузкой, Demand-Side Management (DSM), Управление энергопотреблением, Оптимизация энергопотребления, Снижение затрат на электроэнергию, Энергоэффективность, Энергосбережение, Мониторинг энергопотребления, Контроль энергопотребления, Автоматизация управления нагрузкой, Управление пиковой нагрузкой, Снижение пиковой мощности, Demand Response (Управление спросом), Интеграция с программами управления спросом, Решения для энергоэффективности, Энергетический менеджмент, Системы управления энергопотреблением, Программное обеспечение для управления энергопотреблением"
