#baseURL = "https://house-intellect.github.io/automated-load-management-system/"
baseURL = "https://автоматическое-управление-нагрузкой.рф"
# The "title" of your website
url = "https://автоматическое-управление-нагрузкой.рф"

title = "Система Адаптивного Управления Нагрузкой"
author = "house-intellect"
languageCode = "ru"
DefaultContentLanguage = "ru"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = false  # Disable relative URLs
image = "https://автоматическое-управление-нагрузкой.рф/img/Отключение второстепенных нагрузок при превышении заданного порога мощности с настраиваемыми приоритетами.webp"
# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-YMDXXMEB0E"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']
  copyright = "house-intellect"
  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "Защита от перегрузки за счет пошагового автоматического отключения второстепенных потребителей"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Система Адаптивного Управления Нагрузкой"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Отключение второстепенных нагрузок при превышении заданного порога мощности с настраиваемыми приоритетами"
    meta_og_description = "Защита от перегрузки за счет пошагового автоматического отключения второстепенных потребителей"
    meta_og_type = "website"
    meta_og_url = "https://автоматическое-управление-нагрузкой.рф"
    meta_og_image = "https://автоматическое-управление-нагрузкой.рф/img/alms.webp"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"
    meta_og_title = "Система Адаптивного Управления Нагрузкой"
    keywords = "Автоматическое отключение при перегрузке, САУН, Система Адаптивного Управления Нагрузкой, Управление энергопотреблением, Оптимизация энергопотребления, Энергоэффективность, Энергосбережение, Мониторинг энергопотребления, Контроль энергопотребления, Автоматизация управления нагрузкой, Управление пиковой нагрузкой, Снижение пиковой мощности, Решения для энергоэффективности, Энергетический менеджмент, Системы управления энергопотреблением, Программное обеспечение для управления энергопотреблением, ABB DMTME-I-485, Sonoff, Ewelink, IoT, Промышленная автоматизация, Телеметрия, Виртуальные порты, .Net Framework, WPF, C#"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Проекты"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Новости"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "О нас"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Контакты"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Главная"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/house-intellect"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
