curl -X POST "https://api.indexnow.org/indexnow" \
     -H "Content-Type: application/json" \
     -d '{
  "host": "xn--80aealotwbjpid2k.xn--p1ai",
  "key": "39c54f9ef36247ad89ce28006318c488",
  "keyLocation": "https://xn--80aealotwbjpid2k.xn--p1ai/39c54f9ef36247ad89ce28006318c488.txt",
  "urlList": [
    "https://xn--80aealotwbjpid2k.xn--p1ai/products/energy_management_app/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/index/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/автоматизация/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/blog/automatic-power-corridor-correction/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/blog/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/промышленная-автоматизация/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/технологии/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/управление-мощностью/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/управление-энергопотреблением/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/энергосбережение/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/энергосбережения/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/abb/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/abb/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/автоматическое-отключение-при-перегрузке/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/blog/abb/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/телеметрия/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/телеметрия/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/blog/automatic-power-factor-correction/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/коэффициент-мощности/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/ewelink/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/iot/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/sonoff/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/асу-тп/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/интернет-вещей/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/интернет-вещей/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/коммутационные-устройства/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/blog/sonoff-ewelink/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/промышленная-автоматизация/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/умный-дом/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/умный-дом/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/blog/iot-relays/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/products/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/windows/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/автоматизированные/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/виртуальные-порты/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/данных/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/интерфейсы-связи/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/about/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/tags/поддержка/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/blog/windows-support/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/промышленные/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/сбора/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/categories/системы/",
    "https://xn--80aealotwbjpid2k.xn--p1ai/contact/"
  ]
}'
