curl -X POST "https://api.indexnow.org/indexnow" \
     -H "Content-Type: application/json" \
     -d '{
  "host": "offline-smarthome-scenarios.pro",
  "key": "39c54f9ef36247ad89ce28006318c488",
  "keyLocation": "https://offline-smarthome-scenarios.pro/39c54f9ef36247ad89ce28006318c488.txt",
  "urlList": [
    "https://offline-smarthome-scenarios.pro/products/energy_management_app/",
    "https://offline-smarthome-scenarios.pro/",
    "https://offline-smarthome-scenarios.pro/categories/",
    "https://offline-smarthome-scenarios.pro/tags/index/",
    "https://offline-smarthome-scenarios.pro/tags/",
    "https://offline-smarthome-scenarios.pro/tags/автоматизация/",
    "https://offline-smarthome-scenarios.pro/blog/automatic-power-corridor-correction/",
    "https://offline-smarthome-scenarios.pro/blog/",
    "https://offline-smarthome-scenarios.pro/tags/промышленная-автоматизация/",
    "https://offline-smarthome-scenarios.pro/categories/технологии/",
    "https://offline-smarthome-scenarios.pro/tags/управление-мощностью/",
    "https://offline-smarthome-scenarios.pro/tags/управление-энергопотреблением/",
    "https://offline-smarthome-scenarios.pro/tags/энергосбережение/",
    "https://offline-smarthome-scenarios.pro/categories/энергосбережения/",
    "https://offline-smarthome-scenarios.pro/tags/abb/",
    "https://offline-smarthome-scenarios.pro/categories/abb/",
    "https://offline-smarthome-scenarios.pro/tags/автоматическое-отключение-при-перегрузке/",
    "https://offline-smarthome-scenarios.pro/blog/abb/",
    "https://offline-smarthome-scenarios.pro/tags/телеметрия/",
    "https://offline-smarthome-scenarios.pro/categories/телеметрия/",
    "https://offline-smarthome-scenarios.pro/blog/automatic-power-factor-correction/",
    "https://offline-smarthome-scenarios.pro/tags/коэффициент-мощности/",
    "https://offline-smarthome-scenarios.pro/tags/ewelink/",
    "https://offline-smarthome-scenarios.pro/tags/iot/",
    "https://offline-smarthome-scenarios.pro/tags/sonoff/",
    "https://offline-smarthome-scenarios.pro/categories/асу-тп/",
    "https://offline-smarthome-scenarios.pro/tags/интернет-вещей/",
    "https://offline-smarthome-scenarios.pro/categories/интернет-вещей/",
    "https://offline-smarthome-scenarios.pro/tags/коммутационные-устройства/",
    "https://offline-smarthome-scenarios.pro/blog/sonoff-ewelink/",
    "https://offline-smarthome-scenarios.pro/categories/промышленная-автоматизация/",
    "https://offline-smarthome-scenarios.pro/tags/умный-дом/",
    "https://offline-smarthome-scenarios.pro/categories/умный-дом/",
    "https://offline-smarthome-scenarios.pro/blog/iot-relays/",
    "https://offline-smarthome-scenarios.pro/products/",
    "https://offline-smarthome-scenarios.pro/tags/windows/",
    "https://offline-smarthome-scenarios.pro/categories/автоматизированные/",
    "https://offline-smarthome-scenarios.pro/tags/виртуальные-порты/",
    "https://offline-smarthome-scenarios.pro/categories/данных/",
    "https://offline-smarthome-scenarios.pro/tags/интерфейсы-связи/",
    "https://offline-smarthome-scenarios.pro/about/",
    "https://offline-smarthome-scenarios.pro/tags/поддержка/",
    "https://offline-smarthome-scenarios.pro/blog/windows-support/",
    "https://offline-smarthome-scenarios.pro/categories/промышленные/",
    "https://offline-smarthome-scenarios.pro/categories/сбора/",
    "https://offline-smarthome-scenarios.pro/categories/системы/",
    "https://offline-smarthome-scenarios.pro/contact/"
  ]
}
'
